import type { Mascota, IdMascota } from "@/tipos";

/* ==========================================================
   HABITOTCHI · los dibujos de las mascotas
   ==========================================================
   Cada mascota tiene tres etapas y una paleta propia. Los
   dibujos son texto: una fila por string, una letra por
   pixel, "." para el vacio.

   Las letras, iguales en las seis:
     N contorno · C cuerpo · L panza clara · S sombra
     D detalle propio · K acento · M mejilla
     O y B las pone la carita encima (ver caras.ts)

   Medidas: bebe 12x11, joven 14x15, adulta 16x19. Los tests
   de tests/datos-mascotas.test.ts verifican que sigan
   parejas, centradas y sin pixeles sueltos.
   ========================================================== */

export const MASCOTAS: Record<IdMascota, Mascota> = {
  dragoncito: {
    nombre: "Dragoncito",
    colores: {
      N: "#16401f",
      C: "#3f8a45",
      L: "#6cb867",
      S: "#2b6330",
      D: "#e8d08a",
      K: "#f0e3b0",
      M: "#e89ab0",
      O: "#0d2410",
      B: "#e6f7c8",
    },
    etapas: {
      bebe: {
        cara: { x: 2, y: 3 },
        pixeles: [
          "..D......D..",
          ".NDN....NDN.",
          ".NLLNNNNLLN.",
          "NLLLLLLLLLLN",
          "NLLLLLLLLLLN",
          "NMLLLLLLLLMN",
          "NLLLLLLLLLLN",
          ".NLLLLLLLLN.",
          ".NSLLLLLLSN.",
          "..NNSSSSNN..",
          "...KK..KK...",
        ],
      },
      joven: {
        cara: { x: 3, y: 4 },
        pixeles: [
          "..D........D..",
          "..DN......ND..",
          ".NLLNNNNNNLLN.",
          ".NLLLLLLLLLLN.",
          "NLLLLLLLLLLLLN",
          "NLLLLLLLLLLLLN",
          "NMLLLLLLLLLLMN",
          "NLLLLLLLLLLLLN",
          "DNLLLLLLLLLLND",
          "DDNLLLLLLLLNDD",
          ".NSLLLLLLLLSN.",
          ".NSSLLLLLLSSN.",
          "..NSSSLLSSSN..",
          "..NNSSSSSSNN..",
          "...KK....KK...",
        ],
      },
      adulto: {
        cara: { x: 4, y: 5 },
        pixeles: [
          "...D........D...",
          "...DD......DD...",
          "..NLLNNNNNNLLN..",
          "..NLLLLLLLLLLN..",
          ".NLLLLLLLLLLLLN.",
          ".NLLLLLLLLLLLLN.",
          "NLLLLLLLLLLLLLLN",
          "NMLLLLLLLLLLLLMN",
          "NLLLLLLLLLLLLLLN",
          "DNLLLLLLLLLLLLND",
          "DDNLLLLLLLLLLNDD",
          "DDDNLLLLLLLLNDDD",
          ".DDNSLLLLLLSNDD.",
          "..DNSSLLLLSSND..",
          "..NSSSLLLLSSSN..",
          "..NSSSSLLSSSSN..",
          "..NNSSSSSSSSNN..",
          "...KK......KK...",
          "...KK......KK...",
        ],
      },
    },
  },
  gatito: {
    nombre: "Gatito",
    colores: {
      N: "#5a3410",
      C: "#d9873c",
      L: "#f0b978",
      S: "#b06a24",
      D: "#8a4a14",
      K: "#f7ddb8",
      M: "#e89ab0",
      O: "#2e1a06",
      B: "#fff2dc",
    },
    etapas: {
      bebe: {
        cara: { x: 2, y: 3 },
        pixeles: [
          ".NN......NN.",
          ".NDN....NDN.",
          ".NLLNNNNLLN.",
          "NLLLLLLLLLLN",
          "NLDLLLLLLDLN",
          "NMLLLLLLLLMN",
          "NLLLLLLLLLLN",
          ".NLLLKKLLLN.",
          ".NSLLLLLLSN.",
          "..NNSSSSNN..",
          "...NN..NN...",
        ],
      },
      joven: {
        cara: { x: 3, y: 4 },
        pixeles: [
          ".NN........NN.",
          ".NDN......NDN.",
          ".NLDN....NDLN.",
          ".NLLNNNNNNLLN.",
          "NLLLLLLLLLLLLN",
          "NLDLLLLLLLLDLN",
          "NMLLLLLLLLLLMN",
          "NLLLLLLLLLLLLN",
          "NLLLLLKKLLLLLN",
          ".NLLLLLLLLLLN.",
          ".NSLLLLLLLLSN.",
          ".NSSLLLLLLSSN.",
          "..NSSSLLSSSN..",
          "..NNSSSSSSNN..",
          "...NN....NN...",
        ],
      },
      adulto: {
        cara: { x: 4, y: 5 },
        pixeles: [
          "..NN........NN..",
          "..NDN......NDN..",
          "..NLDN....NDLN..",
          "..NLLDN..NDLLN..",
          "..NLLNNNNNNLLN..",
          ".NLLLLLLLLLLLLN.",
          ".NLDLLLLLLLLDLN.",
          "NMLLLLLLLLLLLLMN",
          "NLLLLLLLLLLLLLLN",
          "NLLLLLLKKLLLLLLN",
          "NLDLLLLLLLLLLDLN",
          ".NLLLLLLLLLLLLN.",
          ".NSLLLLLLLLLLSN.",
          ".NSSLLLLLLLLSSN.",
          "..NSSSLLLLSSSN..",
          "..NSSSSLLSSSSN..",
          "..NNSSSSSSSSNN..",
          "...NN......NN...",
          "...NN......NN...",
        ],
      },
    },
  },
  conejito: {
    nombre: "Conejito",
    colores: {
      N: "#4a4258",
      C: "#b9b0cf",
      L: "#e0d9ee",
      S: "#8f87a8",
      D: "#e3b7c9",
      K: "#fbf6ff",
      M: "#e89ab0",
      O: "#2b2436",
      B: "#ffffff",
    },
    etapas: {
      bebe: {
        cara: { x: 2, y: 3 },
        pixeles: [
          "...NN..NN...",
          "...ND..DN...",
          "..NLDNNDLN..",
          "NLLLLLLLLLLN",
          "NLLLLLLLLLLN",
          "NMLLLLLLLLMN",
          "NLLLLLLLLLLN",
          ".NLLLKKLLLN.",
          ".NSLLLLLLSN.",
          "..NNSSSSNN..",
          "...NN..NN...",
        ],
      },
      joven: {
        cara: { x: 3, y: 4 },
        pixeles: [
          "....NN..NN....",
          "....ND..DN....",
          "....ND..DN....",
          "...NLDNNDLN...",
          "NLLLLLLLLLLLLN",
          "NLLLLLLLLLLLLN",
          "NMLLLLLLLLLLMN",
          "NLLLLLLLLLLLLN",
          "NLLLLLKKLLLLLN",
          ".NLLLLLLLLLLN.",
          ".NSLLLLLLLLSN.",
          ".NSSLLLLLLSSN.",
          "..NSSSLLSSSN..",
          "..NNSSSSSSNN..",
          "...NN....NN...",
        ],
      },
      adulto: {
        cara: { x: 4, y: 5 },
        pixeles: [
          ".....NN..NN.....",
          ".....ND..DN.....",
          ".....ND..DN.....",
          ".....ND..DN.....",
          "...NLLDNNDLLN...",
          ".NLLLLLLLLLLLLN.",
          ".NLLLLLLLLLLLLN.",
          "NMLLLLLLLLLLLLMN",
          "NLLLLLLLLLLLLLLN",
          "NLLLLLLKKLLLLLLN",
          "NLLLLLLLLLLLLLLN",
          ".NLLLLLLLLLLLLN.",
          ".NSLLLLLLLLLLSN.",
          ".NSSLLLLLLLLSSN.",
          "..NSSSLLLLSSSN..",
          "..NSSSSLLSSSSN..",
          "..NNSSSSSSSSNN..",
          "...NN......NN...",
          "...NN......NN...",
        ],
      },
    },
  },
  pollito: {
    nombre: "Pollito",
    precio: 150,
    colores: {
      N: "#6b4a0e",
      C: "#e0b32e",
      L: "#f5dd7a",
      S: "#c08f18",
      D: "#cfa021",
      K: "#e07a1e",
      M: "#e89ab0",
      O: "#3a2a06",
      B: "#fff6d0",
    },
    etapas: {
      bebe: {
        cara: { x: 2, y: 3 },
        pixeles: [
          "....NNNN....",
          "..NNLLLLNN..",
          ".NLLLLLLLLN.",
          "NLLLLLLLLLLN",
          "NLLLLLLLLLLN",
          "NMLLLLLLLLMN",
          "NLLLLLLLLLLN",
          ".NLLLKKLLLN.",
          ".NSLLLLLLSN.",
          "..NNSSSSNN..",
          "....KK.KK...",
        ],
      },
      joven: {
        cara: { x: 4, y: 4 },
        pixeles: [
          ".....NNNN.....",
          "...NNLLLLNN...",
          "..NLLLLLLLLN..",
          ".NLLLLLLLLLLN.",
          ".NLLLLLLLLLLN.",
          "NLLLLLLLLLLLLN",
          "NMLLLLLLLLLLMN",
          "NLLLLLLLLLLLLN",
          "NDLLLLLKKLLLDN",
          "NDLLLLLLLLLLDN",
          ".NDLLLLLLLLDN.",
          ".NSLLLLLLLLSN.",
          "..NSSLLLLSSN..",
          "...NNSSSSNN...",
          "....KK..KK....",
        ],
      },
      adulto: {
        cara: { x: 5, y: 5 },
        pixeles: [
          "......NNNN......",
          "....NNLLLLNN....",
          "...NLLLLLLLLN...",
          "..NLLLLLLLLLLN..",
          ".NLLLLLLLLLLLLN.",
          ".NLLLLLLLLLLLLN.",
          "NLLLLLLLLLLLLLLN",
          "NMLLLLLLLLLLLLMN",
          "NLLLLLLLLLLLLLLN",
          "NLLLLLLKKLLLLLLN",
          "NDDLLLLLLLLLLDDN",
          "NDDLLLLLLLLLLDDN",
          ".NDDLLLLLLLLDDN.",
          ".NSLLLLLLLLLLSN.",
          "..NSSLLLLLLSSN..",
          "..NSSSLLLLSSSN..",
          "...NNSSSSSSNN...",
          "....KK....KK....",
          "...KKK....KKK...",
        ],
      },
    },
  },
  osito: {
    nombre: "Osito",
    precio: 200,
    colores: {
      N: "#3a2712",
      C: "#8a5f34",
      L: "#a87a4a",
      S: "#63421f",
      D: "#5c3d1e",
      K: "#dcbc8e",
      M: "#e89ab0",
      O: "#241708",
      B: "#f6e6cc",
    },
    etapas: {
      bebe: {
        cara: { x: 2, y: 3 },
        pixeles: [
          ".NN......NN.",
          "NDDN....NDDN",
          ".NLLNNNNLLN.",
          "NLLLLLLLLLLN",
          "NLLLLLLLLLLN",
          "NMLLLLLLLLMN",
          "NLLLKKKKLLLN",
          ".NLLKKKKLLN.",
          ".NSLLLLLLSN.",
          "..NNSSSSNN..",
          "...NN..NN...",
        ],
      },
      joven: {
        cara: { x: 3, y: 3 },
        pixeles: [
          ".NN........NN.",
          "NDDN......NDDN",
          "NDDN......NDDN",
          ".NLLNNNNNNLLN.",
          "NLLLLLLLLLLLLN",
          "NLLLLLLLLLLLLN",
          "NMLLLLLLLLLLMN",
          "NLLLLKKKKLLLLN",
          "NLLLLKKKKLLLLN",
          ".NLLLLLLLLLLN.",
          ".NSLLKKKKLLSN.",
          ".NSSLKKKKLSSN.",
          "..NSSSLLSSSN..",
          "..NNSSSSSSNN..",
          "..NNN....NNN..",
        ],
      },
      adulto: {
        cara: { x: 4, y: 4 },
        pixeles: [
          "..NN........NN..",
          ".NDDN......NDDN.",
          ".NDDN......NDDN.",
          "..NLLNNNNNNLLN..",
          ".NLLLLLLLLLLLLN.",
          ".NLLLLLLLLLLLLN.",
          "NMLLLLLLLLLLLLMN",
          "NLLLLLLLLLLLLLLN",
          "NLLLLLKKKKLLLLLN",
          "NLLLLLKKKKLLLLLN",
          ".NLLLLKKKKLLLLN.",
          ".NLLLLLLLLLLLLN.",
          ".NSLLLKKKKLLLSN.",
          ".NSSLLKKKKLLSSN.",
          "..NSSLKKKKLSSN..",
          "..NSSSLLLLSSSN..",
          "..NNSSSSSSSSNN..",
          "..NNN......NNN..",
          "..NNN......NNN..",
        ],
      },
    },
  },
  dinosaurio: {
    nombre: "Dinosaurio",
    precio: 300,
    colores: {
      N: "#10403a",
      C: "#2f8f7a",
      L: "#57bfa6",
      S: "#1f6b5c",
      D: "#e8a33c",
      K: "#f2d9a0",
      M: "#e89ab0",
      O: "#0a2b26",
      B: "#dff6e8",
    },
    etapas: {
      bebe: {
        cara: { x: 2, y: 3 },
        pixeles: [
          "...DD..DD...",
          "..NDDNNDDN..",
          ".NLLLLLLLLN.",
          "NLLLLLLLLLLN",
          "NLLLLLLLLLLN",
          "NMLLLLLLLLMN",
          "NLLLLLLLLLLN",
          ".NLLLLLLLLN.",
          ".NSLLLLLLSN.",
          "..NNSSSSNN..",
          "...KK..KK...",
        ],
      },
      joven: {
        cara: { x: 3, y: 4 },
        pixeles: [
          "....DD..DD....",
          "...NDDNNDDN...",
          ".NLLLLLLLLLLN.",
          ".NLLLLLLLLLLN.",
          "NLLLLLLLLLLLLN",
          "NLLLLLLLLLLLLN",
          "NMLLLLLLLLLLMN",
          "NLLLLLLLLLLLLN",
          "NLLLLLLLLLLLLN",
          ".NLLLLLLLLLLNN",
          ".NSLLLLLLLLSLN",
          ".NSSLLLLLLSSNN",
          "..NSSSLLSSSN..",
          "..NNSSSSSSNN..",
          "...KK....KK...",
        ],
      },
      adulto: {
        cara: { x: 4, y: 5 },
        pixeles: [
          ".....DD..DD.....",
          "....NDDNNDDN....",
          "..NLLLLLLLLLLN..",
          "..NLLLLLLLLLLN..",
          ".NLLLLLLLLLLLLN.",
          ".NLLLLLLLLLLLLN.",
          "NLLLLLLLLLLLLLLN",
          "NMLLLLLLLLLLLLMN",
          "NLLLLLLLLLLLLLLN",
          "NLLLLLLLLLLLLLLN",
          "NLLLLLLLLLLLLLLN",
          ".NLLLLLLLLLLLLNN",
          ".NSLLLLLLLLLLSLN",
          ".NSSLLLLLLLLSSLN",
          "..NSSSLLLLSSSSNN",
          "..NSSSSLLSSSSN..",
          "..NNSSSSSSSSNN..",
          "...KK......KK...",
          "..KKK......KKK..",
        ],
      },
    },
  },
};
