import type { Textos } from "./es";

/* ==========================================================
   HABITOTCHI · the English texts
   ==========================================================
   Typed against es.ts: if a key is added there and not here,
   TypeScript fails the build instead of letting Spanish leak
   into someone's app.

   ---------- WORD ORDER IS NOT THE SPANISH ONE ----------
   The placeholders carry names ({n}, {etapa}) precisely so
   each language can put them where its own grammar wants
   them. "Faltan {n} días para {etapa}" becomes "{n} good days
   to go until {etapa}" — same holes, different order.

   ---------- KEEPING THE VOICE ----------
   The Spanish is written in warm, informal rioplatense: it
   talks to you, not at you. The English aims for the same
   register — plain and friendly, never corporate. "Anotá tu
   peso" is "Jot down your weight", not "Please record your
   weight measurement".
   ========================================================== */

export const EN: Textos = {
  /* ---------- tabs ---------- */
  pantallaHogar: "Home",
  pantallaAlimentacion: "Food",
  pantallaEjercicio: "Exercise",
  pantallaHobbies: "Hobbies",
  pantallaTrabajo: "Work",
  pantallaCalendario: "Calendar",
  pantallaSalud: "Health",
  pantallaJuegos: "Games",
  pantallaTienda: "Shop",

  /* ---------- the device ---------- */
  aparatoPantalla: "Device screen",
  aparatoBotones: "Device buttons",
  aparatoNavegacion: "Tab navigation",
  aparatoIrA: "Go to {nombre}",
  aparatoAnterior: "Previous tab",
  aparatoSiguiente: "Next tab",
  aparatoAbrirAjustes: "Open settings",
  cerrar: "Close",

  marcadorPuntos: "points",
  marcadorRacha: "streak",
  marcadorMonedas: "coins",
  pieCementerio: "memorial",
  pieHoy: "today",
  pieEstadisticas: "stats",

  faltanDiasBuenos: {
    uno: "{n} good day to go until {etapa}",
    otros: "{n} good days to go until {etapa}",
  },
  yaEsAdulta: "Your pet is all grown up!",

  /* ---------- growth stages ---------- */
  etapaBebe: "baby",
  etapaJoven: "young",
  etapaAdulto: "grown-up",

  /* ---------- Home ---------- */
  elegiTuMascota: "Pick your pet",
  ponleNombre: "give it a name",
  listo: "Done",
  ultimosSieteDias: "Last 7 days",
  noDesbloqueada: "You haven't unlocked {mascota} yet. It's in the shop.",

  /* ---------- Food ---------- */
  tusMetasDeHoy: "Today's goals",
  queComiste: "What did you eat",
  hoyKcal: "Today · {n} kcal",
  ejemploComida: "chicken and rice",
  kcal: "kcal",
  agregar: "Add",
  sinComidasHoy: "You haven't logged any meals today.",
  sugerenciaKcal: "{comida}: about {n} kcal",
  notaCalorias: "Calories are rough estimates from a built-in dictionary with Argentine and everyday dishes. You can type in English or Spanish.",

  /* ---------- Exercise ---------- */
  tuMetaDeHoy: "Today's goal",
  comoVenis: "How you're doing",
  loDeHoy: "Today",
  cardio: "Cardio",
  pesas: "Weights",
  pasos: "Steps",
  minutos: "minutes",
  km: "km",
  series: "sets",
  repeticiones: "reps",
  peso: "weight",
  nombreDelEjercicio: "exercise name",
  agregarEjercicioPropio: "Add an exercise that isn't on the list",
  pasosDeHoy: "steps today",
  sinEjercicioHoy: "You haven't logged anything today.",
  notaPasos: "Steps are entered by hand.",

  /* ---------- Hobbies ---------- */
  queEstasLeyendo: "What you're reading",
  librosTerminados: "Books finished",
  queEstasEscuchando: "What you're listening to",
  discosEscuchados: "Albums you've heard",
  otrasActividades: "Other activities",
  titulo: "title",
  autor: "author",
  album: "album",
  artista: "artist",
  guardar: "Save",
  queTeParecio: "What did you think?",
  termine: 'Finished "{titulo}"',
  escuche: 'Listened to "{titulo}"',
  sinLibroActual: "You haven't added a book yet.",
  sinLibrosLeidos: "No books finished yet. Each one earns 30 coins.",
  sinDiscoActual: "You haven't added an album yet.",
  sinDiscosEscuchados: "No albums logged yet.",
  noSePudoBuscarLibro: "Couldn't look up the book.",
  noSePudoBuscarDisco: "Couldn't look up the album.",

  /* ---------- Work ---------- */
  horasDeHoy: "Hours today",
  pendientes: "To-do",
  anotarPendiente: "add something to do",
  sinPendientes: "Nothing left to do!",
  teQuedan: { uno: "{n} left.", otros: "{n} left." },
  horas: "hours",
  sinTrabajoHoy: "You haven't logged any hours today.",

  /* ---------- Calendar ---------- */
  anotarAlgo: "jot something down",
  nadaEseDia: "Nothing on that day.",
  googleCalendar: "Google Calendar",
  conectar: "Connect",
  desconectar: "Disconnect",
  trayendoEventos: "Fetching your events…",
  eventosDeGoogle: "Your events show up next to your own notes. They can't be edited or deleted from here.",
  ofrecerGoogle: "To see your Google events here too. It only reads them — it can't change anything in your calendar.",
  sinTitulo: "(untitled)",
  permisoVencido: "Your access expired. Tap Connect again.",
  googleNoContesto: "Google didn't respond properly.",
  noSeCargoGoogle: "Couldn't load Google's script.",
  googleNoDisponible: "Google isn't available.",
  conexionCancelada: "Connection cancelled.",
  sinConectarCalendario: "You haven't connected your calendar yet.",

  /* ---------- Health ---------- */
  comoTeSentis: "How are you feeling?",
  medicaciones: "Medication",
  registroDePeso: "Weight log",
  cicloMenstrual: "Menstrual cycle",
  notaOpcional: "Note (optional)",
  nombre: "name",
  dosis: "dose",
  ejemploHorarios: "09:00, 21:00",
  kgDeHoy: "kg today",
  dias: "days",
  cuandoEmpezo: "When it started",
  sinAnimoHoy: "You haven't logged how you feel today.",
  sinMedicaciones: "No medication added.",
  sinPeso: "Nothing logged yet.",
  sinCiclo: "Nothing logged yet.",
  ultimoRegistro: "Last entry: {fecha}",
  estaSemana: "This week: {resumen}",
  pesoVacio: "Log your weight at least twice to see how it moves.",
  disclaimerSalud: "Nothing you log here adds or takes away points. It's your record, not a goal to hit.",

  /* ---------- Games ---------- */
  viborita: "Snake",
  pong: "Pong",
  saltador: "Jumper",
  ayudaViborita: "Swipe on the screen to turn (or use the arrows).",
  ayudaPong: "Move the paddle with your finger or the mouse. The first 5 rallies are slow.",
  ayudaSaltador: "Tap the screen to jump over the obstacles.",
  puntos: "Score: {n}",
  record: "Best: {n}",
  jugar: "Play",
  elegiUnJuego: "Pick a game to start.",
  tocaJugar: "Tap Play to start.",
  dale: "Go!",
  recordNuevo: { uno: "New best! {n} point.", otros: "New best! {n} points." },
  perdiste: "You lost with {n}. Your best is {record}.",
  arriba: "Up",
  abajo: "Down",
  izquierda: "Left",
  derecha: "Right",

  /* ---------- Shop ---------- */
  monedasTotal: "{n} coins",
  mascotas: "Pets",
  accesorios: "Accessories",
  fondosDePantalla: "Screen themes",
  logros: "Achievements",
  poner: "Wear",
  sacar: "Remove",
  puesto: "On",
  yaDesbloqueada: "{nombre}, already unlocked",
  desbloqueado: "{nombre} unlocked!",
  teFaltanMonedas: { uno: "You need {n} more coin.", otros: "You need {n} more coins." },
  yaLoTenes: "You already have that.",
  comoGanarMonedas: "You earn coins by hitting your daily goals. Every good day counts, and every 7 in a row gives a bonus.",
  notaTienda: "Anything you buy stays unlocked forever.",

  /* ---------- Settings ---------- */
  ajustes: "Settings",
  sobreVos: "About you",
  queMostrar: "What to show",
  tuCuenta: "Your account",
  privacidad: "Privacy",
  tusDatos: "Your data",
  idioma: "Language",
  comoTeLlamas: "What's your name?",
  anios: "age",
  pronombre: "Pronoun",
  pesoKg: "weight (kg)",
  alturaCm: "height (cm)",
  notaPeso: "Your weight is used to estimate exercise calories, and it's saved to your account along with the rest of your data.",
  mostrarCiclo: "Menstrual cycle log, in Health",
  notaCiclo: "If you turn it off, the panel disappears from the Health tab. Nothing you logged is deleted: it comes back if you turn it on again.",
  conectadaComo: "Signed in as {email}",
  cambiarContrasena: "Change password",
  contrasenaNueva: "new password",
  cerrarSesion: "Sign out",
  contrasenaCambiada: "Done, password changed.",
  noSePudoCambiarContrasena: "Couldn't change the password.",
  descargarMisDatos: "Download my data",
  restaurarCopia: "Restore a backup",
  borrarTodo: "Delete everything",
  copiaDescargada: "Done, your backup was downloaded.",
  datosRestaurados: "Data restored. Reload the page to see it.",
  archivoInvalido: "That file doesn't look like a Habitotchi backup.",
  borrando: "Deleting…",
  confirmarBorrar1: "Are you sure? This deletes everything you've logged and can't be undone.",
  confirmarBorrar2: "Really, there's no going back. Delete everything?",
  noSePudoBorrarNube: "Couldn't delete from your account. Nothing was deleted.",
  verPolitica: "Read the privacy policy",
  notaPolitica: "The policy is in Spanish even if you use the app in English: it's a legal document, and translating it badly would be worse than not translating it.",
  notaDatos: "Everything is saved to your account, so you'll find it on any device. The downloaded backup is for keeping a copy outside the app.",

  /* ---------- the login gate ---------- */
  entraATuCuenta: "Sign in",
  crearUnaCuenta: "Create an account",
  recuperarContrasena: "Reset your password",
  tuMail: "your email",
  contrasena: "password",
  mantenerSesion: "Keep me signed in",
  aceptoPolitica: "I accept the",
  laPoliticaDePrivacidad: "privacy policy",
  debeAceptarPolitica: "You need to accept the privacy policy to create an account.",
  entrar: "Sign in",
  crearCuenta: "Create account",
  enviarmeElLink: "Send me the link",
  olvideMiContrasena: "I forgot my password",
  volverAEntrar: "Back to sign in",
  elegiContrasenaNueva: "Choose a new password",
  minimoSeisCaracteres: "It needs at least 6 characters.",
  revisaTuMail: "We sent an email to {email}. Tap the link inside and you're in.",
  linkDeRecuperacion: "If there's an account with that email, you'll get a link to set a new password.",
  migrarDatos: "Want to move what you've already logged on this device into your new account?",
  unSegundo: "One moment…",
  algoSalioMal: "Something went wrong.",
  llegasteATodas: "You hit all your goals!",
  faltaAlgunaMeta: "Still a goal to go.",
  estaSemanaBuenos: "This week · {n} of 7 good days",
  totalDiasBuenos: "Total good days",
  mostrarContrasena: "Show the password",
  ocultarContrasena: "Hide the password",

  /* cloud messages */
  credencialesInvalidas: "Wrong email or password.",
  mailYaRegistrado: "There's already an account with that email.",
  contrasenaCorta: "The password needs at least 6 characters.",
  mailInvalido: "That email doesn't look valid.",
  nubeNoDisponible: "The cloud account isn't available.",
  noSePudoSubir: "Couldn't upload your data: {detalle}",
  noSePudoTraer: "Couldn't fetch your data: {detalle}",

  /* ---------- the A / B / C modals ---------- */
  cementerio: "Memorial",
  sinCementerio: "You haven't lost a pet yet.",
  llegoA: "reached {etapa}",
  detalleDeHoy: "Today",
  estadisticas: "Stats",
  rachaActual: "Current streak",
  mejorRacha: "Best streak",
  diasBuenos: "Good days",
  totalMonedas: "Coins earned",
  dia: { uno: "{n} day", otros: "{n} days" },

  /* ---------- the goodbye ---------- */
  descansa: "{nombre} is resting. You can pick a new pet.",
  chau: "Bye, {nombre}.",
  unFantasmita: "A little ghost floating up",
  unaTumba: "A gravestone that reads R.I.P.",

  /* ---------- shared pieces ---------- */
  borrar: "Delete",
  cancelar: "Cancel",
  sumarA: "Add {paso} to {nombre}",
  restarDe: "Subtract {paso} from {nombre}",
  editarMeta: "Edit the {nombre} goal",
  calificacion: "Rating",
  deCinco: "{n} out of 5",
  semana: "Week",
  mes: "Month",
  anio: "Year",
  graficoVacio: "Not enough entries for a chart yet.",
  sinRegistros: "No entries yet",
  caloriasQuemadas: "Calories burned today (rough): {kcal} kcal in {min} minutes.",
  sinSesionesHoy: "No sessions logged today.",
  sinActividades: "No activities logged yet.",
  sinHorasHoy: "No hours logged today.",
  sinPendientesCargados: "Nothing on your to-do list.",
  quePendiente: "what you need to do",
  comoGanarDetalle: "You earn 10 coins for every good day, plus 50 extra every 7 days in a row. Games don't give coins: the idea is that playing shouldn't compete with looking after yourself.",

  /* ---------- dates ---------- */
  meses: "January,February,March,April,May,June,July,August,September,October,November,December",
  /* Monday to Sunday. English needs two letters where one
     would collide: Tuesday/Thursday and Saturday/Sunday. */
  inicialesSemana: "M,Tu,W,Th,F,Sa,Su",
  abreviaturaSemana: "wk {n}",

  /* ---------- catalogue: habits ---------- */
  habitoAgua: "Water",
  habitoComida: "Meals logged",
  habitoEjercicio: "Exercise",
  habitoLectura: "Reading",
  habitoTrabajo: "Work / study",
  habitoDulces: "Sweets",
  unidadVasos: "glasses",
  unidadComidas: "meals",
  unidadMin: "min",
  unidadHoras: "hours",
  unidadVeces: "times",

  /* ---------- catalogue: pets ---------- */
  mascotaDragoncito: "Dragon",
  mascotaGatito: "Kitty",
  mascotaConejito: "Bunny",
  mascotaPollito: "Chick",
  mascotaOsito: "Bear",
  mascotaDinosaurio: "Dino",

  /* ---------- catalogue: accessories and themes ---------- */
  accesorioMonio: "Bow",
  accesorioSombrero: "Hat",
  accesorioLentes: "Glasses",
  accesorioCorona: "Crown",
  fondoClasico: "Classic",
  fondoAtardecer: "Sunset",
  fondoNoche: "Night",
  fondoAlgodon: "Cotton",

  /* ---------- catalogue: meals, moods, hobbies, work ---------- */
  comidaDesayuno: "Breakfast",
  comidaAlmuerzo: "Lunch",
  comidaMerienda: "Snack",
  comidaCena: "Dinner",
  comidaSnack: "Bite",

  animoMuybien: "Great",
  animoBien: "Good",
  animoNormal: "Okay",
  animoBajon: "Down",
  animoMal: "Awful",

  hobbyAmigos: "Friends",
  hobbyFamilia: "Family",
  hobbyPintura: "Painting",
  hobbyVideojuegos: "Video games",
  hobbySeries: "Series",
  hobbyPaseos: "Walks",
  hobbyFotografia: "Photography",
  hobbyOtro: "Other",

  trabajoTrabajo: "Work",
  trabajoEstudio: "Study",

  pronombreElla: "she",
  pronombreEl: "he",
  pronombreElle: "they",
  pronombreOtro: "rather not say",

  /* ---------- catalogue: cardio ---------- */
  cardioCinta: "Treadmill",
  cardioRunning: "Running",
  cardioSoga: "Jump rope",
  cardioBici: "Cycling",
  cardioNatacion: "Swimming",
  cardioEliptica: "Elliptical",
  cardioBaile: "Dancing",
  cardioOtro: "Other cardio",

  /* ---------- catalogue: strength ---------- */
  grupoPiernas: "Legs",
  grupoEspalda: "Back",
  grupoPecho: "Chest & shoulders",
  grupoBrazos: "Arms",
  grupoCore: "Core",
  grupoOtros: "Other",
  grupoMisEjercicios: "My exercises",

  fuerzaSentadilla: "Squat",
  fuerzaPrensa: "Leg press",
  fuerzaEstocadas: "Lunges",
  fuerzaPesoMuerto: "Deadlift",
  fuerzaCurlFemoral: "Leg curl",
  fuerzaExtensionCuad: "Leg extension",
  fuerzaGemelos: "Calf raises",
  fuerzaHipThrust: "Hip thrust",
  fuerzaDominadas: "Pull-ups",
  fuerzaRemo: "Row",
  fuerzaJalonPecho: "Lat pulldown",
  fuerzaRemoMancuerna: "Dumbbell row",
  fuerzaPressBanca: "Bench press",
  fuerzaPressInclinado: "Incline press",
  fuerzaAperturas: "Chest fly",
  fuerzaFlexiones: "Push-ups",
  fuerzaPressMilitar: "Overhead press",
  fuerzaElevacionesLat: "Lateral raises",
  fuerzaCurlBiceps: "Bicep curl",
  fuerzaTricepsPolea: "Tricep pushdown",
  fuerzaFondos: "Dips",
  fuerzaPlancha: "Plank",
  fuerzaAbdominales: "Crunches",
  fuerzaElevacionPierna: "Leg raises",
  fuerzaOtro: "Other exercise",

  intensidadLeve: "Light (you can talk easily)",
  intensidadModerada: "Moderate (holding a chat is hard)",
  intensidadIntensa: "Hard (you can't talk while doing it)",

  /* ---------- catalogue: achievements ---------- */
  logroPrimerDia: "First step",
  logroPrimerDiaDesc: "Your first good day",
  logroSemana: "One week",
  logroSemanaDesc: "7 good days in total",
  logroMes: "A whole month",
  logroMesDesc: "30 good days in total",
  logroRacha7: "Unstoppable",
  logroRacha7Desc: "7 good days in a row",
  logroRacha30: "Habit formed",
  logroRacha30Desc: "30 good days in a row",
  logroJoven: "Growing up",
  logroJovenDesc: "Your pet reached young",
  logroAdulto: "All grown up",
  logroAdultoDesc: "Your pet reached grown-up",
  logroAgua100: "Well hydrated",
  logroAgua100Desc: "100 glasses of water in total",
  logroEjercicio500: "On the move",
  logroEjercicio500Desc: "500 minutes of exercise",
  logroColeccion: "Collector",
  logroColeccionDesc: "You unlocked every pet",
  logroPrimerLibro: "First read",
  logroPrimerLibroDesc: "You finished your first book",
  logroCincoLibros: "Bookworm",
  logroCincoLibrosDesc: "You finished 5 books",
};
